# Generated by Django 5.2.7 on 2025-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=90000000000, max_length=15),
            preserve_default=False,
        ),
    ]
